name: Java CI com Execução de Servidor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Baixar MySQL Connector
      run: |
        mkdir lib
        curl -L -o lib/mysql-connector.jar https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.2.0/mysql-connector-j-9.2.0.jar

    - name: Compilar Java
      run: |
        mkdir bin
        javac -d bin -cp "lib/mysql-connector.jar" *.java

    - name: Rodar servidor em background
      run: |
        java -cp "bin:lib/mysql-connector.jar" LoginCadastro &
        echo $! > server.pid
        sleep 5

    - name: Testar resposta do servidor
      run: |
        curl --fail --max-time 5 http://localhost:8089 || (echo "Falha ao conectar ao servidor" && exit 1)

    - name: Finalizar servidor
      run: |
        kill $(cat server.pid)
